"""Shared, config-driven detection of machine-generated source files.

Used by the orchestrator (to advise the user) and the magic-number scanner
(to optionally suppress findings on generated files). The marker list lives
in config (detection.generated_markers) — no hardcoded rules in call sites.
"""
from __future__ import annotations

from backend.app_config import CFG

# defaults cover AUTOSAR RTE / MICROSAR / common codegen banners; override or
# extend via config detection.generated_markers
_DEFAULT_MARKERS = (
    "do not edit", "do not modify", "automatically generated",
    "auto-generated", "autogenerated", "generated by", "rte generator",
    "microsar", "this file was generated", "file requires user modifications",
    "@generated", "code generator",
)


def generated_marker(code: str) -> str:
    """Return the first generated-file marker found near the top of the file
    (config-driven), or '' if the file does not look machine-generated."""
    scan_chars = int(CFG.get("detection.generated_scan_chars", 4000))
    markers = CFG.get("detection.generated_markers", list(_DEFAULT_MARKERS))
    head = code[:scan_chars].lower()
    for m in markers:
        if str(m).lower() in head:
            return str(m)
    return ""
