"""L1b — Hardcoding scanner (AST-based, deterministic).

Flags, with exact line numbers and zero hallucination:
- magic numbers in expressions (config-tunable allowlist; module-level
  UPPER_CASE constant assignments and default args are skipped by default)
- hardcoded URLs, absolute filesystem paths, IP addresses in string literals
- embedded secrets: credential-looking assignments and known key formats

Fixes for these are generated by the fix engine (extract-to-constant /
move-to-config), then AST-validated.
"""
from __future__ import annotations

import ast
import re

from backend.app_config import CFG
from backend.models import Layer, Severity, Violation

_URL_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*://\S+")
_WIN_PATH_RE = re.compile(r"^[A-Za-z]:[\\/](?:[^\\/\n]+[\\/]?)+")
_UNIX_PATH_RE = re.compile(r"^/(?:usr|home|etc|var|opt|tmp|kaggle|mnt|data)(?:/[^\s]*)?$")
_IP_RE = re.compile(r"^(?:\d{1,3}\.){3}\d{1,3}(?::\d+)?$")
_AWS_KEY_RE = re.compile(r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b")
_GENERIC_KEY_RE = re.compile(r"^[A-Za-z0-9+/_\-]{32,}={0,2}$")
_SECRET_NAME_RE = re.compile(r"(password|passwd|pwd|secret|api_?key|access_?key|auth_?token|token)", re.I)
_LOCALHOST = {"127.0.0.1", "0.0.0.0", "localhost"}


class _Annotator(ast.NodeVisitor):
    """Attach parent pointers so we can inspect a literal's context."""

    def visit(self, node: ast.AST):
        for child in ast.iter_child_nodes(node):
            child._parent = node  # type: ignore[attr-defined]
        super().generic_visit(node)
        return node


def _is_constant_assignment(node: ast.AST) -> bool:
    p = getattr(node, "_parent", None)
    if isinstance(p, ast.Assign):
        return all(
            isinstance(t, ast.Name) and t.id.isupper() for t in p.targets
        )
    if isinstance(p, ast.AnnAssign):
        return isinstance(p.target, ast.Name) and p.target.id.isupper()
    return False


def _in_default_args(node: ast.AST) -> bool:
    p = getattr(node, "_parent", None)
    return isinstance(p, ast.arguments)


def _assigned_name(node: ast.AST) -> str:
    p = getattr(node, "_parent", None)
    if isinstance(p, ast.Assign) and p.targets and isinstance(p.targets[0], ast.Name):
        return p.targets[0].id
    if isinstance(p, ast.AnnAssign) and isinstance(p.target, ast.Name):
        return p.target.id
    if isinstance(p, ast.keyword) and p.arg:
        return p.arg
    return ""


def run_hardcode_layer(code: str) -> list[Violation]:
    if not CFG.get("hardcode.enabled", True):
        return []
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return []
    _Annotator().visit(tree)

    allowed = set(CFG.get("hardcode.magic_numbers.allowed", [0, 1, -1]))
    num_on = CFG.get("hardcode.magic_numbers.enabled", True)
    skip_const = CFG.get("hardcode.magic_numbers.skip_constant_assignments", True)
    skip_defaults = CFG.get("hardcode.magic_numbers.skip_default_args", True)
    flag_urls = CFG.get("hardcode.strings.flag_urls", True)
    flag_paths = CFG.get("hardcode.strings.flag_absolute_paths", True)
    flag_ips = CFG.get("hardcode.strings.flag_ip_addresses", True)
    secrets_on = CFG.get("hardcode.secrets.enabled", True)

    lines = code.splitlines()
    out: list[Violation] = []
    counter = 0
    seen: set[tuple[int, str]] = set()

    def add(line: int, rule: str, sev: Severity, msg: str, sugg: str):
        nonlocal counter
        if (line, rule) in seen:
            return
        seen.add((line, rule))
        counter += 1
        out.append(Violation(
            id=f"hardcode-{counter}", layer=Layer.HARDCODE, rule=rule,
            severity=sev, line=line,
            snippet=(lines[line - 1].strip() if 0 < line <= len(lines) else ""),
            message=msg, suggestion=sugg,
        ))

    for node in ast.walk(tree):
        if not isinstance(node, ast.Constant):
            continue
        line = getattr(node, "lineno", 0)
        val = node.value

        if isinstance(val, bool):  # bool is a subclass of int — never a magic number
            continue

        if num_on and isinstance(val, (int, float)) and val not in allowed:
            if skip_const and _is_constant_assignment(node):
                continue
            if skip_defaults and _in_default_args(node):
                continue
            add(line, "magic-number", Severity.LOW,
                f"Magic number {val!r} embedded in code",
                "Extract to a named constant or move to configuration")

        elif isinstance(val, str) and val:
            name = _assigned_name(node)
            if secrets_on:
                if _AWS_KEY_RE.search(val):
                    add(line, "embedded-secret", Severity.CRITICAL,
                        "String matches an AWS access key format",
                        "Remove the key and load it from environment/secret manager")
                    continue
                if _SECRET_NAME_RE.search(name) and len(val) >= 6 and not val.startswith("$"):
                    add(line, "embedded-secret", Severity.CRITICAL,
                        f"Credential-looking value assigned to '{name}'",
                        "Load secrets from environment variables, never source code")
                    continue
                if _SECRET_NAME_RE.search(name) and _GENERIC_KEY_RE.match(val):
                    add(line, "embedded-secret", Severity.CRITICAL,
                        f"High-entropy value assigned to secret-named variable '{name}'",
                        "Load secrets from environment variables, never source code")
                    continue
            if flag_urls and _URL_RE.match(val) and not _is_constant_assignment(node):
                add(line, "hardcoded-url", Severity.MEDIUM,
                    f"Hardcoded URL '{val[:60]}'",
                    "Move URLs to configuration")
            elif flag_ips and _IP_RE.match(val) and val.split(":")[0] not in _LOCALHOST:
                add(line, "hardcoded-ip", Severity.MEDIUM,
                    f"Hardcoded IP address '{val}'",
                    "Move network addresses to configuration")
            elif flag_paths and (_WIN_PATH_RE.match(val) or _UNIX_PATH_RE.match(val)):
                add(line, "hardcoded-path", Severity.MEDIUM,
                    f"Hardcoded absolute path '{val[:60]}'",
                    "Move filesystem paths to configuration or derive at runtime")
    return out
