"""L0 — Spell layer (language-generic).

Dictionary-based (codespell dictionary): only *known* misspellings are
flagged, keeping false positives near zero. The language plugin supplies
tokens (identifiers / comments / strings); identifiers are split on
snake_case and camelCase boundaries so `recieveData` is caught while
legitimate abbreviations (`cnt`, `idx`) never fire (not in the dictionary).

Fixes:
- identifier misspelling -> file-wide rename, gated by the language's
  syntax validator
- comment/string misspelling -> single-line word replacement
"""
from __future__ import annotations

import re
from functools import lru_cache
from pathlib import Path

from backend.app_config import CFG
from backend.languages.base import LanguagePlugin
from backend.models import Fix, Layer, Severity, Violation

_WORD_RE = re.compile(r"[A-Za-z]+")
_CAMEL_RE = re.compile(r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+|\d+")


# codespell ships several curated dictionaries; names here map to its files.
# main/code/rare are all human-curated misspelling->correction pairs (near-zero
# FP). The dialect files (en-GB->en-US, Oxford) are intentionally NOT default:
# flagging 'initialise'/'colour' as wrong is a false positive for teams using
# British spelling.
_CODESPELL_FILES = {
    "main": "dictionary.txt",
    "code": "dictionary_code.txt",
    "rare": "dictionary_rare.txt",
    "informal": "dictionary_informal.txt",
    "usage": "dictionary_usage.txt",
    "en-GB-to-en-US": "dictionary_en-GB_to_en-US.txt",
    "en-to-en-OX": "dictionary_en_to_en-OX_AUTOGENERATED.txt",
    "names": "dictionary_names.txt",
}


def _configured_dictionaries() -> tuple[str, ...]:
    names = CFG.get("spell.dictionaries", ["main", "code", "rare"])
    return tuple(str(n) for n in names)


@lru_cache(maxsize=8)
def _dictionary_for(names: tuple[str, ...]) -> dict[str, tuple[list[str], bool]]:
    """Merge the named codespell dictionaries into word -> (suggestions,
    autofix_ok). Earlier dictionaries win on conflict."""
    import codespell_lib

    data_dir = Path(codespell_lib.__file__).parent / "data"
    table: dict[str, tuple[list[str], bool]] = {}
    for name in names:
        fname = _CODESPELL_FILES.get(name)
        if not fname:
            continue
        path = data_dir / fname
        if not path.exists():
            continue
        for raw in path.read_text(encoding="utf-8").splitlines():
            if "->" not in raw:
                continue
            wrong, correction = raw.split("->", 1)
            wrong = wrong.strip().lower()
            ambiguous = correction.endswith(",")
            parts = [p.strip() for p in correction.split(",") if p.strip()]
            if not wrong or not parts or wrong in table:
                continue
            table[wrong] = (parts, (len(parts) == 1) and not ambiguous)
    return table


def _dictionary() -> dict[str, tuple[list[str], bool]]:
    """The active merged misspelling dictionary (config-driven)."""
    return _dictionary_for(_configured_dictionaries())


def _split_subwords(identifier: str) -> list[str]:
    out: list[str] = []
    for chunk in identifier.split("_"):
        out.extend(_CAMEL_RE.findall(chunk))
    return out


def _match_case(original: str, replacement: str) -> str:
    if original.isupper():
        return replacement.upper()
    if original[:1].isupper():
        return replacement[:1].upper() + replacement[1:]
    return replacement


def _is_external_identifier(ident: str) -> bool:
    """True if the identifier is defined outside this file (generated / BSW
    API), so a file-local rename would break the build. Prefix list is
    config-driven (spell.external_prefixes)."""
    prefixes = CFG.get("spell.external_prefixes", [
        "Rte_", "Os_", "Dem_", "Det_", "Com_", "NvM_", "EcuM_", "BswM_",
        "Can", "Lin", "Fr_", "Eth_", "Dcm_", "PduR_", "Std_", "VStdLib_",
        "Mcu_", "Port_", "Dio_", "Adc_", "Pwm_", "Gpt_", "Spi_", "Wdg_",
    ])
    return any(ident.startswith(p) for p in prefixes)


def _check_word(word: str, min_len: int, allow: set[str]) -> tuple[list[str], bool] | None:
    lw = word.lower()
    if len(lw) < min_len or lw in allow:
        return None
    return _dictionary().get(lw)


def _derive_project_vocabulary(tokens, min_identifiers: int) -> set[str]:
    """Learn the codebase's own naming conventions dynamically.

    A subword used across >= min_identifiers DISTINCT identifiers is treated
    as intentional project vocabulary (e.g. 'Shft' in ShftSpdSig, ShftSpdCtrl,
    ...). A one-off dictionary misspelling (a real typo like 'Treshold') never
    reaches that count, so it stays reportable. No hardcoded word list — the
    accepted terms are inferred from the code under review.
    """
    from collections import defaultdict

    subword_to_idents: dict[str, set[str]] = defaultdict(set)
    for tok in tokens:
        if tok.kind == "identifier":
            for sub in _split_subwords(tok.text):
                if len(sub) >= 2:
                    subword_to_idents[sub.lower()].add(tok.text)
    return {sw for sw, idents in subword_to_idents.items()
            if len(idents) >= min_identifiers}


def run_spell_layer(code: str, plugin: LanguagePlugin) -> list[Violation]:
    cfg = CFG
    if not cfg.get("spell.enabled", True):
        return []
    min_len = int(cfg.get("spell.min_word_length", 4))
    allow = {w.lower() for w in cfg.get("spell.allowlist", [])}
    single_only = bool(cfg.get("spell.autofix_single_suggestion_only", True))

    tokens = plugin.spell_tokens(code)

    # DYNAMIC false-positive suppression: learn the codebase's own naming
    # conventions instead of relying on a hardcoded abbreviation list.
    if cfg.get("spell.dynamic_vocabulary", True):
        vocab = _derive_project_vocabulary(
            tokens, int(cfg.get("spell.vocab_min_identifiers", 3)))
        allow = allow | vocab

    violations: list[Violation] = []
    seen_identifiers: set[str] = set()
    seen_words: set[tuple[int, str]] = set()
    lines = code.splitlines()
    baseline_ok, _ = plugin.validate_syntax(code)
    counter = 0

    def next_id() -> str:
        nonlocal counter
        counter += 1
        return f"spell-{counter}"

    for tok in tokens:
        if tok.kind == "identifier" and cfg.get("spell.check_identifiers", True):
            if tok.text in seen_identifiers:
                continue
            for sub in _split_subwords(tok.text):
                hit = _check_word(sub, min_len, allow)
                if not hit:
                    continue
                suggestions, autofix_ok = hit
                seen_identifiers.add(tok.text)
                corrected_sub = _match_case(sub, suggestions[0])
                corrected_ident = tok.text.replace(sub, corrected_sub)
                # An identifier defined OUTSIDE this file (generated/BSW API like
                # Rte_*, Dem_*, ...) must not be renamed here — the real name
                # lives in a generated header, so a file-local rename breaks the
                # build. Report the typo, but no rename fix.
                external = _is_external_identifier(tok.text)
                fix = None
                if (autofix_ok or not single_only) and not external:
                    from backend.diffutil import display_diff

                    fixed_code = re.sub(
                        rf"\b{re.escape(tok.text)}\b", corrected_ident, code)
                    ok, note = plugin.validate_syntax(fixed_code)
                    valid = ok or not baseline_ok
                    if not baseline_ok:
                        note = "renamed file-wide (original didn't parse — syntax gate skipped)"
                    elif ok:
                        note = f"renamed file-wide; {note}"
                    fix = Fix(
                        start_line=tok.line, end_line=tok.line,
                        replacement=display_diff(code, fixed_code), file_wide=True,
                        fixed_code=fixed_code if valid else None,
                        validated=valid, validation_notes=note,
                    )
                suggestion = (
                    "Generated/external API name — fix the typo in the generator "
                    "config, not here (renaming would break the build)"
                    if external else
                    f"Rename to '{corrected_ident}' (all occurrences)")
                violations.append(Violation(
                    id=next_id(), layer=Layer.SPELL, rule="spell-identifier",
                    severity=Severity.LOW, line=tok.line, col=tok.col,
                    snippet=(lines[tok.line - 1].strip()
                             if tok.line - 1 < len(lines) else tok.text),
                    message=f"Identifier '{tok.text}' contains misspelling "
                            f"'{sub}' -> {', '.join(suggestions)}",
                    suggestion=suggestion,
                    fix=fix,
                    no_autofix=external,   # never let the fix engine rename it
                ))
                break  # one report per identifier

        elif tok.kind in ("comment", "string"):
            if tok.kind == "comment" and not cfg.get("spell.check_comments", True):
                continue
            if tok.kind == "string" and not cfg.get("spell.check_strings", True):
                continue
            for m in _WORD_RE.finditer(tok.text):
                # a word immediately followed by an apostrophe is a
                # contraction or possessive ("couldn't", "user's") — correct
                # English, not the apostrophe-less typo codespell lists
                # ("couldn" -> couldn't). Skip it to avoid the false positive.
                if tok.text[m.end():m.end() + 1] in ("'", "’", "ʼ"):
                    continue
                for sub in _CAMEL_RE.findall(m.group(0)):
                    hit = _check_word(sub, min_len, allow)
                    if not hit:
                        continue
                    suggestions, autofix_ok = hit
                    line_no = tok.line + tok.text.count("\n", 0, m.start())
                    key = (line_no, sub.lower())
                    if key in seen_words:
                        continue
                    seen_words.add(key)
                    corrected = _match_case(sub, suggestions[0])
                    fix = None
                    if (autofix_ok or not single_only) and line_no - 1 < len(lines):
                        old_line = lines[line_no - 1]
                        new_line = re.sub(rf"\b{re.escape(sub)}\b", corrected, old_line)
                        if new_line != old_line:
                            fix = Fix(
                                start_line=line_no, end_line=line_no,
                                replacement=new_line, validated=True,
                                validation_notes="single-line word replacement",
                            )
                    violations.append(Violation(
                        id=next_id(), layer=Layer.SPELL, rule=f"spell-{tok.kind}",
                        severity=Severity.INFO, line=line_no,
                        snippet=(lines[line_no - 1].strip()
                                 if line_no - 1 < len(lines) else m.group(0)),
                        message=f"Misspelling in {tok.kind}: '{sub}' -> "
                                f"{', '.join(suggestions)}",
                        suggestion=f"Replace with '{corrected}'",
                        fix=fix,
                    ))
    return violations
